FROM python:3.10-bullseye
ENV PYTHONUNBUFFERED=1

WORKDIR /app

COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install gunicorn

COPY . /app/

EXPOSE 5000

CMD ["gunicorn", "--config", "gunicorn_config.py", "wsgi:app"]